---
- name: load systemd file
  copy:
    src: etcd.service
    dest: /usr/lib/systemd/system/
- name: register etcd service
  shell: systemctl daemon-reload 
- name: startup etcd service 
  service:
    name: etcd
    state: started
    enabled: yes
